'use strict';
const $=id=>document.getElementById(id);
let catalog=[],current=null;
const fmt=n=>Number.isFinite(Number(n))?Number(n).toFixed(4):'—';
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
async function api(path,options){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function showSource(){const s=catalog.find(x=>x.symbol===$('symbol').value);$('source').textContent=s?.available?`${s.source} · ${s.source_bar_count} 根 ${s.source_interval}\n${s.first_bar} → ${s.last_bar}\n擷取：${s.observed_at}\n校驗：${s.capture_sha256}`:`來源不可用：${s?.reason||'未取得'}`;$('run').disabled=!s?.available;}
async function history(){const data=await api('/api/replay/runs');const box=$('history');box.replaceChildren();for(const r of data.runs){if(!r.run_id){box.append(node('small',r.status));continue;}const b=node('button',`${r.symbol} · ${r.frozen_at} · holdout ${fmt(r.final_holdout.net_return_pct)}%`);b.onclick=async()=>{try{render(await api('/api/replay/runs/'+encodeURIComponent(r.run_id)));}catch(e){$('status').textContent=e.message;}};box.append(b);}for(const failure of data.failures||[])box.append(node('small',`失敗仍保留：${failure.reason||failure.error_type||failure.status}`));if(!data.runs.length&&!data.failures?.length)box.append(node('small','沒有歷史執行。'));
}
function render(result){current=result;const box=$('result');box.replaceChildren(node('h2',`${result.symbol} · ${result.currency} · 凍結回放結果`));box.append(node('small',`執行：${result.run_id}\n資料時點：${result.source_provenance?.observed_at||'來源時點未取得'}\n最終 holdout：${result.final_holdout.test_start} → ${result.final_holdout.test_end}`));const metrics=node('div',undefined,'grid');for(const [label,value,unit] of [['Holdout 淨報酬',result.final_holdout.net_return_pct,'%'],['成本加倍淨報酬',result.cost_stress.net_return_pct,'%'],['Holdout 最大回撤',result.final_holdout.max_drawdown_pct,'%']]){const d=node('div',undefined,'metric');d.append(node('span',label),node('strong',fmt(value)+unit,value<0?'negative':'positive'));metrics.append(d);}box.append(metrics);const wrap=node('div',undefined,'table-wrap');const table=node('table');const header=node('tr');for(const label of ['區間','測試起迄','成交數','費後報酬','回撤','重建一致'])header.append(node('th',label));table.append(header);const rows=result.folds.map(f=>[`Fold ${f.fold}`,f.test_start,f.test_end,f.simulation]);rows.push(['最終 Holdout',result.final_holdout.test_start,result.final_holdout.test_end,result.final_holdout],['成本加倍',result.final_holdout.test_start,result.final_holdout.test_end,result.cost_stress]);for(const [name,start,end,sim]of rows){const tr=node('tr');for(const text of [name,`${start.slice(0,10)} → ${end.slice(0,10)}`,String(sim.fills),fmt(sim.net_return_pct)+'%',fmt(sim.max_drawdown_pct)+'%',sim.deterministic?'PASS':'FAIL'])tr.append(node('td',text));table.append(tr);}wrap.append(table);box.append(wrap);const canvas=node('canvas');canvas.setAttribute('aria-label','最終 holdout 虛擬 NAV 曲線');canvas.setAttribute('role','img');box.append(canvas);requestAnimationFrame(()=>plot(canvas,result.final_holdout.equity_path));const details=node('details');details.append(node('summary','凍結參數、來源校驗與權限界線'));details.append(node('pre',JSON.stringify({authority:result.authority,live_acceptance:result.live_acceptance,broker_connected:result.broker_connected,config:result.config,config_hash:result.config_hash,source_hash:result.source_hash,source_provenance:result.source_provenance,selection_policy:result.selection_policy,limitations:result.limitations},null,2)));box.append(details);const download=node('button','下載本次原始結果 JSON');download.onclick=()=>{const a=node('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));a.download=current.run_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};box.append(download);}
function plot(canvas,values){if(!Array.isArray(values)||values.length<2)return;const w=canvas.clientWidth||800,h=190;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;const ctx=canvas.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);const lo=Math.min(...values),hi=Math.max(...values),span=Math.max(hi-lo,1);ctx.strokeStyle='#52bcff';ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=15+i/(values.length-1)*(w-30),y=15+(hi-v)/span*(h-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle='#adc7e1';ctx.font='12px sans-serif';ctx.fillText('Holdout NAV · '+fmt(values[0])+' → '+fmt(values.at(-1)),15,h-5);}
$('symbol').onchange=showSource;
$('run-form').onsubmit=async e=>{e.preventDefault();$('run').disabled=true;$('status').textContent='校驗来源、凍結參數並執行歷史回放…';try{const result=await api('/api/replay/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:$('symbol').value,initial_cash:Number($('cash').value),folds:Number($('folds').value),config:{fast:Number($('fast').value),slow:Number($('slow').value)}})});render(result);$('status').textContent='歷史回放結果已讀回；不是 LIVE PAPER 驗收。';await history();}catch(err){$('status').textContent='停止：'+err.message;}finally{showSource();}};
(async()=>{try{catalog=(await api('/api/replay/sources')).sources;showSource();await history();}catch(e){$('status').textContent='來源／結果服務失敗：'+e.message;}})();
